import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Plus, Pencil, Trash2, Eye, EyeOff, LogOut, Shield, Loader2 } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import type { App } from '../lib/types';

export default function AdminDashboardPage() {
  const { signOut } = useAuth();
  const navigate = useNavigate();
  const [apps, setApps] = useState<App[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const r = await fetch('/api/apps?include_hidden=true'); if (!r.ok) throw new Error('Failed to load apps'); const d = await r.json(); setApps(Array.isArray(d) ? d : []); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const remove = async (id: number) => { if (!confirm('Delete this app permanently?')) return; const r = await fetch('/api/apps', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); if (r.ok) setApps(a => a.filter(x => x.id !== id)); else setError('Delete failed'); };
  const logout = async () => { await signOut(); navigate('/admin/login', { replace: true }); };
  return <div className="min-h-screen bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-gray-100"><header className="sticky top-0 z-10 bg-white/90 dark:bg-gray-900/90 backdrop-blur border-b border-gray-200 dark:border-gray-800"><div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-violet-600 flex items-center justify-center"><Shield className="text-white w-5 h-5" /></div><div><b className="block">Agon Agent</b><span className="text-xs text-gray-500">Administration</span></div></div><div className="flex gap-2"><Link to="/admin/edit" className="px-4 py-2 rounded-xl bg-violet-600 text-white text-sm font-semibold inline-flex items-center gap-2"><Plus className="w-4 h-4" /> New app</Link><button onClick={logout} className="px-3 py-2 rounded-xl bg-gray-100 dark:bg-gray-800 text-sm"><LogOut className="w-4 h-4" /></button></div></div></header><main className="max-w-7xl mx-auto px-4 py-8"><div className="flex justify-between items-end mb-6"><div><h1 className="text-3xl font-black">Apps</h1><p className="text-sm text-gray-500 mt-1">Manage what appears in the public store.</p></div><span className="text-sm text-gray-500">{apps.length} total</span></div>{error && <p className="mb-4 text-sm text-red-500">{error}</p>}{loading ? <div className="flex justify-center py-20"><Loader2 className="animate-spin" /></div> : <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 overflow-hidden">{apps.length === 0 ? <div className="p-12 text-center text-gray-500">No apps yet.</div> : apps.map(app => <div key={app.id} className="p-4 border-b last:border-b-0 border-gray-200 dark:border-gray-800 flex items-center gap-4"><img src={app.icon_url} alt="" className="w-14 h-14 rounded-xl object-cover" /><div className="flex-1 min-w-0"><b className="block truncate">{app.name}</b><span className="text-xs text-gray-500">v{app.version} · {app.download_count} downloads</span></div><span className={`text-xs px-2 py-1 rounded-full ${app.is_hidden ? 'bg-gray-200 text-gray-600' : 'bg-emerald-100 text-emerald-700'}`}>{app.is_hidden ? <EyeOff className="w-3 h-3 inline" /> : <Eye className="w-3 h-3 inline" />}</span><Link to={`/admin/edit?id=${app.id}`} className="p-2 rounded-lg bg-gray-100 dark:bg-gray-800"><Pencil className="w-4 h-4" /></Link><button onClick={() => remove(app.id)} className="p-2 rounded-lg bg-red-50 text-red-600"><Trash2 className="w-4 h-4" /></button></div>)}</div>}</main></div>;
}
