import { Link } from 'react-router-dom';
import { Search, Moon, Sun, Shield, Menu, X } from 'lucide-react';
import { useTheme } from '../contexts/ThemeContext';
import { useState, useEffect } from 'react';

export default function Header({ onSearch }: { onSearch?: (q: string) => void }) {
  const { theme, toggleTheme } = useTheme();
  const [query, setQuery] = useState('');
  const [mobileOpen, setMobileOpen] = useState(false);
  useEffect(() => { const t = setTimeout(() => onSearch?.(query), 200); return () => clearTimeout(t); }, [query, onSearch]);
  return <header className="sticky top-0 z-40 backdrop-blur-xl bg-white/80 dark:bg-gray-950/80 border-b border-gray-200 dark:border-gray-800"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-16 gap-4"><Link to="/" className="flex items-center gap-2 shrink-0"><div className="w-9 h-9 rounded-xl bg-gradient-to-br from-violet-500 via-fuchsia-500 to-pink-500 flex items-center justify-center shadow-lg"><span className="text-white font-black text-lg">A</span></div><span className="font-black text-xl tracking-tight hidden sm:inline">AppVault</span></Link><div className="flex-1 max-w-xl relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" /><input type="text" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search apps, games, tools…" className="w-full pl-10 pr-4 py-2.5 rounded-xl bg-gray-100 dark:bg-gray-900 border border-transparent focus:border-violet-500 focus:bg-white dark:focus:bg-gray-950 outline-none text-sm transition" /></div><nav className="hidden md:flex items-center gap-1"><Link to="/" className="px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-violet-600 dark:hover:text-violet-400 transition">Store</Link><Link to="/admin" className="px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-violet-600 dark:hover:text-violet-400 transition flex items-center gap-1.5"><Shield className="w-4 h-4" />Admin</Link></nav><div className="flex items-center gap-2"><button onClick={toggleTheme} aria-label="Toggle theme" className="w-10 h-10 rounded-xl bg-gray-100 dark:bg-gray-900 hover:bg-gray-200 dark:hover:bg-gray-800 flex items-center justify-center transition">{theme === 'dark' ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}</button><button onClick={() => setMobileOpen((v) => !v)} className="md:hidden w-10 h-10 rounded-xl bg-gray-100 dark:bg-gray-900 flex items-center justify-center" aria-label="Menu">{mobileOpen ? <X className="w-4 h-4" /> : <Menu className="w-4 h-4" />}</button></div></div>{mobileOpen && <div className="md:hidden py-3 border-t border-gray-200 dark:border-gray-800 flex flex-col gap-1"><Link to="/" onClick={() => setMobileOpen(false)} className="px-3 py-2 rounded-lg text-sm font-medium hover:bg-gray-100 dark:hover:bg-gray-900">Store</Link><Link to="/admin" onClick={() => setMobileOpen(false)} className="px-3 py-2 rounded-lg text-sm font-medium hover:bg-gray-100 dark:hover:bg-gray-900 flex items-center gap-1.5"><Shield className="w-4 h-4" />Admin</Link></div>}</div></header>;
}
